name: Create tag on release

on:
  push:
    branches: [ "release/*" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set develop VERSION env
      run: echo "VERSION=$(echo ${{ github.ref_name }} | sed s/v//)" >> $GITHUB_ENV
    
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Push tag
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.CR_PAT }}
        custom_tag: v${{ env.VERSION }}
