name: Create tag on release

on:
  push:
    branches: [ "release/*" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set develop VERSION env
      run: echo "VERSION=$(echo ${{ github.ref_name }} | sed s/v//)" >> $GITHUB_ENV
    
    - uses: rickstaa/action-create-tag@v1
      with:
        tag: v${{ env.VERSION }}
        message: "Version ${{ env.VERSION }}"
